<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2hQksnJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2hQksnJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2hQksnJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2hQksnJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2hQksnJ\App_KernelDevDebugContainer([
    'container.build_hash' => '2hQksnJ',
    'container.build_id' => '57485979',
    'container.build_time' => 1640448811,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2hQksnJ');
