<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA56ozAe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA56ozAe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA56ozAe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA56ozAe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA56ozAe\App_KernelDevDebugContainer([
    'container.build_hash' => 'A56ozAe',
    'container.build_id' => '55bd5da5',
    'container.build_time' => 1640500604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA56ozAe');
